### ISSUE TITLE
assertion failed: snapshot_index < replica.next_snapshot_index

### ISSUE THREAD

**Issue by w41ter** [engula/engula#990]
In log:

```
2022-08-15T04:13:33.063904Z  INFO engula_server::node::replica::state: replica 1062 node 1 become leader of group 6 at term 91 epoch 113
2022-08-15T04:13:33.067405Z  INFO engula_server::raftgroup::snap::create: replica 1062 begin create snapshot at /home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/0
2022-08-15T04:13:33.073486Z  INFO engula_server::node::replica::fsm: group 6 replica 1062 enter join and add voters [1091] learners [] remove [901], former voters [901, 1038, 1062] learners [1091]
2022-08-15T04:13:33.073737Z  INFO engula_server::node::replica::state: replica 1062 node 1 is ready for serving requests of group 6 at term 91
2022-08-15T04:13:33.074110Z  INFO engula_server::raftgroup::snap::create: replica 1062 begin create snapshot at /home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/1
2022-08-15T04:13:33.281363Z  INFO engula_server::raftgroup::snap::create: replica 1062 begin create snapshot at /home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/2
2022-08-15T04:13:33.560649Z  INFO engula_server::raftgroup::snap::create: replica 1062 begin create snapshot at /home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/0
2022-08-15T04:13:34.060106Z  INFO engula_server::raftgroup::snap::create: replica 1062 begin create snapshot at /home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/0
2022-08-15T04:13:34.062083Z  INFO engula_server::raftgroup::snap::create: replica 1062 create snapshot /home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/0 success
2022-08-15T04:13:34.062127Z  INFO engula_server::raftgroup::snap: replica 1062 install snap 0, dir /home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/0
2022-08-15T04:13:34.062186Z  INFO engula_server::raftgroup::snap::create: replica 1062 create snapshot success
2022-08-15T04:13:34.071440Z  INFO engula_server::raftgroup::snap::create: replica 1062 create snapshot /home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/1 success
2022-08-15T04:13:34.071452Z  WARN engula_server::root::schedule: shed leader in source replica fail, retry in next tick group=5 replica=1021 err=NotLeader(0, 8, Some(ReplicaDesc { id: 105, node_id: 2, role: Voter }))
thread 'tokio-runtime-worker' panicked at 'assertion failed: snapshot_index < replica.next_snapshot_index', src/server/src/raftgroup/snap/mod.rs:199:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-08-15T04:13:34.071488Z  WARN engula_server::root::schedule: shed leader in source replica fail, retry in next tick group=5 replica=1021 err=NotLeader(0, 8, Some(ReplicaDesc { id: 105, node_id: 2, role: Voter }))
```

In gdb:

```
(gdb) frame 14
#14 0x000055a4f051ca05 in engula_server::raftgroup::snap::SnapManager::install (self=0x7f9060037798, replica_id=1062, dir_name=..., meta=0x7f90600378d0)
    at src/server/src/raftgroup/snap/mod.rs:199
199                     debug_assert!(snapshot_index < replica.next_snapshot_index);
(gdb) info local
snapshot_id = <optimized out>
snapshot_index = 1
name = alloc::borrow::Cow<str>::Borrowed("1")
parent = 0x7f909486ee60
parent = &std::path::Path {data_ptr: 0x7f8fdd9609e0, length: 75}
parent = core::option::Option<&std::path::Path>::Some(&std::path::Path {data_ptr: 0x7f8fdd9609e0, length: 75})
replica = 0x7f90703553c8
inner = std::sync::mutex::MutexGuard<engula_server::raftgroup::snap::SnapManagerInner> {lock: 0x7f902c00c588, poison: std::sync::poison::Guard {panicking: false}}
(gdb) print *replica
$1 = engula_server::raftgroup::snap::ReplicaSnapManager {base_dir: std::path::PathBuf {inner: "/home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062"}, next_snapshot_index: 1, snapshots: Vec(size=1) = {engula_server::raftgroup::snap::SnapshotInfo {snapshot_id: Vec(size=1) = {
        48}, base_dir: std::path::PathBuf {inner: "/home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/0"}, meta: engula_server::serverpb::v1::SnapshotMeta {apply_state: core::option::Option<engula_server::serverpb::v1::EntryId>::Some(engula_server::serverpb::v1::EntryId {index: 89829, term: 90}), group_desc: core::option::Option<engula_api::server::v1::GroupDesc>::Some(engula_api::server::v1::GroupDesc {id: 6, epoch: 113, shards: Vec(size=1) = {
              engula_api::server::v1::ShardDesc {id: 11, collection_id: 9, partition: core::option::Option<engula_api::server::v1::shard_desc::Partition>::Some(engula_api::server::v1::shard_desc::Partition::Hash(engula_api::server::v1::shard_desc::HashPartition {slot_id: 2, slots: 5}))}}, replicas: Vec(size=4) = {
              engula_api::server::v1::ReplicaDesc {id: 901, node_id: 4, role: 0}, engula_api::server::v1::ReplicaDesc {id: 1038, node_id: 0, role: 0},
              engula_api::server::v1::ReplicaDesc {id: 1062, node_id: 1, role: 0}, engula_api::server::v1::ReplicaDesc {id: 1091, node_id: 3, role: 1}}}), files: Vec(size=1) = {
          engula_server::serverpb::v1::SnapshotFile {name: Vec(size=10) = {68, 65, 84, 65, 47, 48, 46, 115, 115,
              116}, crc32: 359869051, size: 59129856}}}, ref_count: 0, created_at: std::time::Instant (std::sys::unix::time::inner::Instant {t: std::sys::unix::time::Timespec {tv_sec: 7579, tv_nsec: 443796966}})}}}
(gdb) frame 15                                                                                                                                                                      #15 0x000055a4f03b32b0 in engula_server::raftgroup::snap::create::create_snapshot::{async_fn#0} () at src/server/src/raftgroup/snap/create.rs:107                                   107         Ok(snap_mgr.install(replica_id, &snap_dir, &snap_meta))                                                                                                                 (gdb) info local                                                                                                                                                                    snap_meta = engula_server::serverpb::v1::SnapshotMeta {apply_state: core::option::Option<engula_server::serverpb::v1::EntryId>::Some(engula_server::serverpb::v1::EntryId {index: 89830, term: 90}), group_desc: core::option::Option<engula_api::server::v1::GroupDesc>::Some(engula_api::server::v1::GroupDesc {id: 6, epoch: 114, shards: Vec(size=1) = {
        engula_api::server::v1::ShardDesc {id: 11, collection_id: 9, partition: core::option::Option<engula_api::server::v1::shard_desc::Partition>::Some(engula_api::server::v1::shard_desc::Partition::Hash(engula_api::server::v1::shard_desc::HashPartition {slot_id: 2, slots: 5}))}}, replicas: Vec(size=4) = {
        engula_api::server::v1::ReplicaDesc {id: 901, node_id: 4, role: 3}, engula_api::server::v1::ReplicaDesc {id: 1038, node_id: 0, role: 0},
        engula_api::server::v1::ReplicaDesc {id: 1062, node_id: 1, role: 0}, engula_api::server::v1::ReplicaDesc {id: 1091, node_id: 3, role: 2}}}), files: Vec(size=1) = {
    engula_server::serverpb::v1::SnapshotFile {name: Vec(size=10) = {68, 65, 84, 65, 47, 48, 46, 115, 115, 116}, crc32: 1944628854, size: 61288468}}}
files = Vec(size=1) = {engula_server::serverpb::v1::SnapshotFile {name: Vec(size=10) = {68, 65, 84, 65, 47, 48, 46, 115, 115, 116}, crc32: 1944628854, size: 61288468}}
apply_state = engula_server::serverpb::v1::EntryId {index: 89830, term: 90}
descriptor = engula_api::server::v1::GroupDesc {id: 6, epoch: 114, shards: Vec(size=1) = {
    engula_api::server::v1::ShardDesc {id: 11, collection_id: 9, partition: core::option::Option<engula_api::server::v1::shard_desc::Partition>::Some(engula_api::server::v1::shard_desc::Partition::Hash(engula_api::server::v1::shard_desc::HashPartition {slot_id: 2, slots: 5}))}}, replicas: Vec(size=4) = {
    engula_api::server::v1::ReplicaDesc {id: 901, node_id: 4, role: 3}, engula_api::server::v1::ReplicaDesc {id: 1038, node_id: 0, role: 0},
    engula_api::server::v1::ReplicaDesc {id: 1062, node_id: 1, role: 0}, engula_api::server::v1::ReplicaDesc {id: 1091, node_id: 3, role: 2}}}
data = std::path::PathBuf {inner: "@\001Rޏ\177\000\000\300\240\001\220\220\177\000\000rkspace/montplex/engula/cluster_test/server/5/log/snap/1062/1/DATA"}
snap_dir = std::path::PathBuf {inner: "/home/patrick/workspace/montplex/engula/cluster_test/server/5/log/snap/1062/1"}
builder = alloc::boxed::Box<dyn engula_server::raftgroup::fsm::SnapshotBuilder, alloc::alloc::Global> {pointer: 0x7f900a315190, vtable: 0x55a4f1f51318}
snap_mgr = 0x7f9060037798
replica_id = 1062
replica_id = 1062
snap_mgr = 0x7f9060037798
builder = alloc::boxed::Box<dyn engula_server::raftgroup::fsm::SnapshotBuilder, alloc::alloc::Global> {pointer: 0x7f900a315190, vtable: 0x55a4f1f51318}
_task_context = core::future::ResumeTy (core::ptr::non_null::NonNull<core::task::wake::Context> {pointer: 0x7f9094873178})
```

**Comment by w41ter** [comment]
Closes it via #996.
